### ISSUE TITLE
How to execute?

### ISSUE THREAD

**Issue by joelra** [silversquirl/bedrock-finder-118#1]
I apologize since I have no experience with zig, but do you have a simple guide on how to use this app?

I have downloaded and installed version 0.10 of Zig (on Windows) and set up my path variables. I then downloaded your code and ran `zig build run` but get an error:

```
.\src\main.zig:18:36: error: expected 1 argument(s), found 2
    const seed_str = (try args.next(arena.allocator())) orelse return error.NotEnoughArgs;
```

That leads me to believe that I need to pass in the seed, though I'm struggling on how to include a command line argument on the zig build run command. I apologize for my lack of experience. Any help would be appreciated!

**Comment by silversquirl** [comment]
Looks like Zig updated and changed some things. I've pushed a fix that should let it compile again.

To provide args, use `zig build run -- SEED RANGE` where SEED is your numerical world seed and RANGE is the search range in blocks.

**Comment by PringlePot** [comment]
It has broken again

**Comment by silversquirl** [comment]
FYI you can now run this online through https://vktec.org.uk/bedrock-finder-118/

If you wanna build it natively for the extra speed, I've updated it so it should work now :)

**Comment by PringlePot** [comment]
Could you maybe explain how to change the pattern?

**Comment by silversquirl** [comment]
See these lines in `src/main.zig`:

https://github.com/silversquirl/bedrock-finder-118/blob/c8c56d2641733d6436d1dee63bbc62432dfa94b0/src/main.zig#L4-L10
